- name: Copiar primer fichero
  copy: src=files/file.n1 dest={{ copiar_directorio_files }}/file.n1

- name: Copiar segundo fichero
  copy: src=files/file.n2 dest={{ copiar_directorio_files }}/file.n2

